Repository kairos-io/kairos, pull requests merged in 2023-05, with the labels that each got.

#1170 :penguin: Add Ubuntu flavors for RPi
  .github/flavors-arm.json
  Earthfile
  docs/content/en/docs/Reference/image_matrix.md
  framework-profile.yaml
  images/Dockerfile.ubuntu-20-lts-arm-rpi
  images/Dockerfile.ubuntu-22-lts-arm-rpi
  images/Dockerfile.ubuntu-arm-rpi
  overlay/files-opensuse-arm-rpi/system/oem/11_persistency.yaml
  overlay/files-rpi/etc/cos/bootargs.cfg
  overlay/files-ubuntu-arm-rpi/etc/default/console-setup
  overlay/files-ubuntu-arm-rpi/etc/elemental/config.yaml
  overlay/files-ubuntu-arm-rpi/system/oem/03-setupcon.yaml
Labels: qa

#1432 :penguin: Use latest for fedora images
  images/Dockerfile.fedora
Labels: area/flavor, chore

#1382 Revert ":robot: Run jobs on ubuntu-latest instead of self-hosted"
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: blocked
