Repository kairos-io/kairos, pull requests merged in 2023-01, with the labels that each got.

#675 Adapt CI to match version generation between build and qemu-bundles-tests steps
  .github/workflows/image.yaml
Labels: chore, ci

#713 :arrow_up: Upgrade urfave/cli to v2
  cmd/agent/main.go
  cmd/profile-build/main.go
  go.mod
  go.sum
Labels: chore

#710 :warning: add tumbleweed flavor
  .circleci/config.yml
  .github/workflows/image-arm.yaml
  .github/workflows/image.yaml
  .github/workflows/release-arm.yaml
  .github/workflows/release.yaml
  Earthfile
  docs/content/en/docs/Advanced/after-install.md
  docs/content/en/docs/Advanced/build.md
  docs/content/en/docs/Examples/core.md
  docs/content/en/docs/Installation/automated.md
  docs/content/en/docs/Installation/netboot.md
  docs/content/en/docs/Installation/raspberry.md
  docs/content/en/docs/Installation/takeover.md
  docs/content/en/docs/Reference/image_matrix.md
  docs/content/en/docs/Upgrade/kubernetes.md
  framework-profile.yaml
  images/Dockerfile.alpine-arm-rpi
  images/Dockerfile.alpine-opensuse-leap
  images/Dockerfile.debian
  images/Dockerfile.fedora
  images/Dockerfile.opensuse-leap
  images/Dockerfile.opensuse-leap-arm-rpi
  images/Dockerfile.opensuse-tumbleweed
  images/Dockerfile.opensuse-tumbleweed-arm-rpi
  images/Dockerfile.rockylinux
  images/Dockerfile.ubuntu
  images/Dockerfile.ubuntu-20-lts
  images/Dockerfile.ubuntu-22-lts
Labels: ci

#670 :art: rename kairos-agent and add sha256 signatures
  .github/workflows/release.yaml
  .goreleaser.yaml
  docs/content/en/docs/Getting started/_index.md
Labels: automation, ci

#741 :sparkles: Integrate documentation to Web UI
  Earthfile
  internal/webui/public/index.html
Labels: area/webui

#768 :bug: Fix tumbleweed iso
  images/Dockerfile.debian
  images/Dockerfile.opensuse-tumbleweed
  images/dracut-missing-overlay-dirs.patch
Labels: bug, area/flavor
