Repository kairos-io/kairos, pull requests merged in 2023-02, with the labels that each got.

#805 :bug: Fix ownership of polkitd rules dir
  overlay/files/system/oem/31_polkit.yaml
Labels: bug

#853 :sparkles: Integrate schema validation
  cmd/agent/main.go
  internal/agent/install.go
  internal/agent/upgrade.go
  internal/agent/validate.go
  internal/agent/validate_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/options.go
  pkg/config/schemas/install_schema_test.go
  pkg/config/schemas/p2p_schema_test.go
  pkg/config/schemas/root_schema.go
  pkg/config/schemas/root_schema_test.go
  pkg/config/schemas/users_schema_test.go
Labels: lane/ux

#906 :wrench: Build docs on arm64
  Earthfile
Labels: ARM
